backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "tattoos"
    preview: false
    label: "Tattoos"
    folder: "content/tattoos"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Tattoo Motive", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Featured Image", name: "featured-image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      
      
